# This file generated by Makefile
# Do not edit. See build-aux directory

font_manager_VALASOURCES = \
./Application.vala \
./Browse.vala \
./Compare.vala \
./Main.vala \
./MainWindow.vala \
./Migration.vala \
./Preferences/Display.vala \
./Preferences/Interface.vala \
./Preferences/Preferences.vala \
./Preferences/Rendering.vala \
./RenderingOptions.vala \
./SideBar.vala \
./State.vala \
./TitleBar.vala 

