/* unicode-blocks.h */
/* THIS IS A GENERATED FILE. CHANGES WILL BE OVERWRITTEN. */
/* Generated by ./gen-unicode-headers.pl */
/* Generated from UCD version 11.0.0 */

#ifndef UNICODE_BLOCKS_H
#define UNICODE_BLOCKS_H

#include <glib.h>
static const char unicode_blocks_strings[] =
  "Basic Latin\0"
  "Latin-1 Supplement\0"
  "Latin Extended-A\0"
  "Latin Extended-B\0"
  "IPA Extensions\0"
  "Spacing Modifier Letters\0"
  "Combining Diacritical Marks\0"
  "Greek and Coptic\0"
  "Cyrillic\0"
  "Cyrillic Supplement\0"
  "Armenian\0"
  "Hebrew\0"
  "Arabic\0"
  "Syriac\0"
  "Arabic Supplement\0"
  "Thaana\0"
  "N'Ko\0"
  "Samaritan\0"
  "Mandaic\0"
  "Syriac Supplement\0"
  "Arabic Extended-A\0"
  "Devanagari\0"
  "Bengali\0"
  "Gurmukhi\0"
  "Gujarati\0"
  "Oriya\0"
  "Tamil\0"
  "Telugu\0"
  "Kannada\0"
  "Malayalam\0"
  "Sinhala\0"
  "Thai\0"
  "Lao\0"
  "Tibetan\0"
  "Myanmar\0"
  "Georgian\0"
  "Hangul Jamo\0"
  "Ethiopic\0"
  "Ethiopic Supplement\0"
  "Cherokee\0"
  "Unified Canadian Aboriginal Syllabics\0"
  "Ogham\0"
  "Runic\0"
  "Tagalog\0"
  "Hanunoo\0"
  "Buhid\0"
  "Tagbanwa\0"
  "Khmer\0"
  "Mongolian\0"
  "Unified Canadian Aboriginal Syllabics Extended\0"
  "Limbu\0"
  "Tai Le\0"
  "New Tai Lue\0"
  "Khmer Symbols\0"
  "Buginese\0"
  "Tai Tham\0"
  "Combining Diacritical Marks Extended\0"
  "Balinese\0"
  "Sundanese\0"
  "Batak\0"
  "Lepcha\0"
  "Ol Chiki\0"
  "Cyrillic Extended-C\0"
  "Sundanese Supplement\0"
  "Vedic Extensions\0"
  "Phonetic Extensions\0"
  "Phonetic Extensions Supplement\0"
  "Combining Diacritical Marks Supplement\0"
  "Latin Extended Additional\0"
  "Greek Extended\0"
  "General Punctuation\0"
  "Superscripts and Subscripts\0"
  "Currency Symbols\0"
  "Combining Diacritical Marks for Symbols\0"
  "Letterlike Symbols\0"
  "Number Forms\0"
  "Arrows\0"
  "Mathematical Operators\0"
  "Miscellaneous Technical\0"
  "Control Pictures\0"
  "Optical Character Recognition\0"
  "Enclosed Alphanumerics\0"
  "Box Drawing\0"
  "Block Elements\0"
  "Geometric Shapes\0"
  "Miscellaneous Symbols\0"
  "Dingbats\0"
  "Miscellaneous Mathematical Symbols-A\0"
  "Supplemental Arrows-A\0"
  "Braille Patterns\0"
  "Supplemental Arrows-B\0"
  "Miscellaneous Mathematical Symbols-B\0"
  "Supplemental Mathematical Operators\0"
  "Miscellaneous Symbols and Arrows\0"
  "Glagolitic\0"
  "Latin Extended-C\0"
  "Coptic\0"
  "Georgian Supplement\0"
  "Tifinagh\0"
  "Ethiopic Extended\0"
  "Cyrillic Extended-A\0"
  "Supplemental Punctuation\0"
  "CJK Radicals Supplement\0"
  "Kangxi Radicals\0"
  "Ideographic Description Characters\0"
  "CJK Symbols and Punctuation\0"
  "Hiragana\0"
  "Katakana\0"
  "Bopomofo\0"
  "Hangul Compatibility Jamo\0"
  "Kanbun\0"
  "Bopomofo Extended\0"
  "CJK Strokes\0"
  "Katakana Phonetic Extensions\0"
  "Enclosed CJK Letters and Months\0"
  "CJK Compatibility\0"
  "CJK Unified Ideographs Extension A\0"
  "Yijing Hexagram Symbols\0"
  "CJK Unified Ideographs\0"
  "Yi Syllables\0"
  "Yi Radicals\0"
  "Lisu\0"
  "Vai\0"
  "Cyrillic Extended-B\0"
  "Bamum\0"
  "Modifier Tone Letters\0"
  "Latin Extended-D\0"
  "Syloti Nagri\0"
  "Common Indic Number Forms\0"
  "Phags-pa\0"
  "Saurashtra\0"
  "Devanagari Extended\0"
  "Kayah Li\0"
  "Rejang\0"
  "Hangul Jamo Extended-A\0"
  "Javanese\0"
  "Myanmar Extended-B\0"
  "Cham\0"
  "Myanmar Extended-A\0"
  "Tai Viet\0"
  "Meetei Mayek Extensions\0"
  "Ethiopic Extended-A\0"
  "Latin Extended-E\0"
  "Cherokee Supplement\0"
  "Meetei Mayek\0"
  "Hangul Syllables\0"
  "Hangul Jamo Extended-B\0"
  "High Surrogates\0"
  "High Private Use Surrogates\0"
  "Low Surrogates\0"
  "Private Use Area\0"
  "CJK Compatibility Ideographs\0"
  "Alphabetic Presentation Forms\0"
  "Arabic Presentation Forms-A\0"
  "Variation Selectors\0"
  "Vertical Forms\0"
  "Combining Half Marks\0"
  "CJK Compatibility Forms\0"
  "Small Form Variants\0"
  "Arabic Presentation Forms-B\0"
  "Halfwidth and Fullwidth Forms\0"
  "Specials\0"
  "Linear B Syllabary\0"
  "Linear B Ideograms\0"
  "Aegean Numbers\0"
  "Ancient Greek Numbers\0"
  "Ancient Symbols\0"
  "Phaistos Disc\0"
  "Lycian\0"
  "Carian\0"
  "Coptic Epact Numbers\0"
  "Old Italic\0"
  "Gothic\0"
  "Old Permic\0"
  "Ugaritic\0"
  "Old Persian\0"
  "Deseret\0"
  "Shavian\0"
  "Osmanya\0"
  "Osage\0"
  "Elbasan\0"
  "Caucasian Albanian\0"
  "Linear A\0"
  "Cypriot Syllabary\0"
  "Imperial Aramaic\0"
  "Palmyrene\0"
  "Nabataean\0"
  "Hatran\0"
  "Phoenician\0"
  "Lydian\0"
  "Meroitic Hieroglyphs\0"
  "Meroitic Cursive\0"
  "Kharoshthi\0"
  "Old South Arabian\0"
  "Old North Arabian\0"
  "Manichaean\0"
  "Avestan\0"
  "Inscriptional Parthian\0"
  "Inscriptional Pahlavi\0"
  "Psalter Pahlavi\0"
  "Old Turkic\0"
  "Old Hungarian\0"
  "Rumi Numeral Symbols\0"
  "Brahmi\0"
  "Kaithi\0"
  "Sora Sompeng\0"
  "Chakma\0"
  "Mahajani\0"
  "Sharada\0"
  "Sinhala Archaic Numbers\0"
  "Khojki\0"
  "Multani\0"
  "Khudawadi\0"
  "Grantha\0"
  "Newa\0"
  "Tirhuta\0"
  "Siddham\0"
  "Modi\0"
  "Mongolian Supplement\0"
  "Takri\0"
  "Ahom\0"
  "Warang Citi\0"
  "Zanabazar Square\0"
  "Soyombo\0"
  "Pau Cin Hau\0"
  "Bhaiksuki\0"
  "Marchen\0"
  "Masaram Gondi\0"
  "Cuneiform\0"
  "Cuneiform Numbers and Punctuation\0"
  "Early Dynastic Cuneiform\0"
  "Egyptian Hieroglyphs\0"
  "Anatolian Hieroglyphs\0"
  "Bamum Supplement\0"
  "Mro\0"
  "Bassa Vah\0"
  "Pahawh Hmong\0"
  "Miao\0"
  "Ideographic Symbols and Punctuation\0"
  "Tangut\0"
  "Tangut Components\0"
  "Kana Supplement\0"
  "Kana Extended-A\0"
  "Nushu\0"
  "Duployan\0"
  "Shorthand Format Controls\0"
  "Byzantine Musical Symbols\0"
  "Musical Symbols\0"
  "Ancient Greek Musical Notation\0"
  "Tai Xuan Jing Symbols\0"
  "Counting Rod Numerals\0"
  "Mathematical Alphanumeric Symbols\0"
  "Sutton SignWriting\0"
  "Glagolitic Supplement\0"
  "Mende Kikakui\0"
  "Adlam\0"
  "Arabic Mathematical Alphabetic Symbols\0"
  "Mahjong Tiles\0"
  "Domino Tiles\0"
  "Playing Cards\0"
  "Enclosed Alphanumeric Supplement\0"
  "Enclosed Ideographic Supplement\0"
  "Miscellaneous Symbols and Pictographs\0"
  "Emoticons\0"
  "Ornamental Dingbats\0"
  "Transport and Map Symbols\0"
  "Alchemical Symbols\0"
  "Geometric Shapes Extended\0"
  "Supplemental Arrows-C\0"
  "Supplemental Symbols and Pictographs\0"
  "CJK Unified Ideographs Extension B\0"
  "CJK Unified Ideographs Extension C\0"
  "CJK Unified Ideographs Extension D\0"
  "CJK Unified Ideographs Extension E\0"
  "CJK Unified Ideographs Extension F\0"
  "CJK Compatibility Ideographs Supplement\0"
  "Tags\0"
  "Variation Selectors Supplement\0"
  "Supplementary Private Use Area-A\0"
  "Supplementary Private Use Area-B\0"
  ;

typedef struct _UnicodeBlock UnicodeBlock;

static const struct _UnicodeBlock
{
  gunichar start;
  gunichar end;
  guint16 block_name_index;
}
unicode_blocks[] =
{
  { 0x0000, 0x007F, 0 },
  { 0x0080, 0x00FF, 12 },
  { 0x0100, 0x017F, 31 },
  { 0x0180, 0x024F, 48 },
  { 0x0250, 0x02AF, 65 },
  { 0x02B0, 0x02FF, 80 },
  { 0x0300, 0x036F, 105 },
  { 0x0370, 0x03FF, 133 },
  { 0x0400, 0x04FF, 150 },
  { 0x0500, 0x052F, 159 },
  { 0x0530, 0x058F, 179 },
  { 0x0590, 0x05FF, 188 },
  { 0x0600, 0x06FF, 195 },
  { 0x0700, 0x074F, 202 },
  { 0x0750, 0x077F, 209 },
  { 0x0780, 0x07BF, 227 },
  { 0x07C0, 0x07FF, 234 },
  { 0x0800, 0x083F, 239 },
  { 0x0840, 0x085F, 249 },
  { 0x0860, 0x086F, 257 },
  { 0x08A0, 0x08FF, 275 },
  { 0x0900, 0x097F, 293 },
  { 0x0980, 0x09FF, 304 },
  { 0x0A00, 0x0A7F, 312 },
  { 0x0A80, 0x0AFF, 321 },
  { 0x0B00, 0x0B7F, 330 },
  { 0x0B80, 0x0BFF, 336 },
  { 0x0C00, 0x0C7F, 342 },
  { 0x0C80, 0x0CFF, 349 },
  { 0x0D00, 0x0D7F, 357 },
  { 0x0D80, 0x0DFF, 367 },
  { 0x0E00, 0x0E7F, 375 },
  { 0x0E80, 0x0EFF, 380 },
  { 0x0F00, 0x0FFF, 384 },
  { 0x1000, 0x109F, 392 },
  { 0x10A0, 0x10FF, 400 },
  { 0x1100, 0x11FF, 409 },
  { 0x1200, 0x137F, 421 },
  { 0x1380, 0x139F, 430 },
  { 0x13A0, 0x13FF, 450 },
  { 0x1400, 0x167F, 459 },
  { 0x1680, 0x169F, 497 },
  { 0x16A0, 0x16FF, 503 },
  { 0x1700, 0x171F, 509 },
  { 0x1720, 0x173F, 517 },
  { 0x1740, 0x175F, 525 },
  { 0x1760, 0x177F, 531 },
  { 0x1780, 0x17FF, 540 },
  { 0x1800, 0x18AF, 546 },
  { 0x18B0, 0x18FF, 556 },
  { 0x1900, 0x194F, 603 },
  { 0x1950, 0x197F, 609 },
  { 0x1980, 0x19DF, 616 },
  { 0x19E0, 0x19FF, 628 },
  { 0x1A00, 0x1A1F, 642 },
  { 0x1A20, 0x1AAF, 651 },
  { 0x1AB0, 0x1AFF, 660 },
  { 0x1B00, 0x1B7F, 697 },
  { 0x1B80, 0x1BBF, 706 },
  { 0x1BC0, 0x1BFF, 716 },
  { 0x1C00, 0x1C4F, 722 },
  { 0x1C50, 0x1C7F, 729 },
  { 0x1C80, 0x1C8F, 738 },
  { 0x1CC0, 0x1CCF, 758 },
  { 0x1CD0, 0x1CFF, 779 },
  { 0x1D00, 0x1D7F, 796 },
  { 0x1D80, 0x1DBF, 816 },
  { 0x1DC0, 0x1DFF, 847 },
  { 0x1E00, 0x1EFF, 886 },
  { 0x1F00, 0x1FFF, 912 },
  { 0x2000, 0x206F, 927 },
  { 0x2070, 0x209F, 947 },
  { 0x20A0, 0x20CF, 975 },
  { 0x20D0, 0x20FF, 992 },
  { 0x2100, 0x214F, 1032 },
  { 0x2150, 0x218F, 1051 },
  { 0x2190, 0x21FF, 1064 },
  { 0x2200, 0x22FF, 1071 },
  { 0x2300, 0x23FF, 1094 },
  { 0x2400, 0x243F, 1118 },
  { 0x2440, 0x245F, 1135 },
  { 0x2460, 0x24FF, 1165 },
  { 0x2500, 0x257F, 1188 },
  { 0x2580, 0x259F, 1200 },
  { 0x25A0, 0x25FF, 1215 },
  { 0x2600, 0x26FF, 1232 },
  { 0x2700, 0x27BF, 1254 },
  { 0x27C0, 0x27EF, 1263 },
  { 0x27F0, 0x27FF, 1300 },
  { 0x2800, 0x28FF, 1322 },
  { 0x2900, 0x297F, 1339 },
  { 0x2980, 0x29FF, 1361 },
  { 0x2A00, 0x2AFF, 1398 },
  { 0x2B00, 0x2BFF, 1434 },
  { 0x2C00, 0x2C5F, 1467 },
  { 0x2C60, 0x2C7F, 1478 },
  { 0x2C80, 0x2CFF, 1495 },
  { 0x2D00, 0x2D2F, 1502 },
  { 0x2D30, 0x2D7F, 1522 },
  { 0x2D80, 0x2DDF, 1531 },
  { 0x2DE0, 0x2DFF, 1549 },
  { 0x2E00, 0x2E7F, 1569 },
  { 0x2E80, 0x2EFF, 1594 },
  { 0x2F00, 0x2FDF, 1618 },
  { 0x2FF0, 0x2FFF, 1634 },
  { 0x3000, 0x303F, 1669 },
  { 0x3040, 0x309F, 1697 },
  { 0x30A0, 0x30FF, 1706 },
  { 0x3100, 0x312F, 1715 },
  { 0x3130, 0x318F, 1724 },
  { 0x3190, 0x319F, 1750 },
  { 0x31A0, 0x31BF, 1757 },
  { 0x31C0, 0x31EF, 1775 },
  { 0x31F0, 0x31FF, 1787 },
  { 0x3200, 0x32FF, 1816 },
  { 0x3300, 0x33FF, 1848 },
  { 0x3400, 0x4DBF, 1866 },
  { 0x4DC0, 0x4DFF, 1901 },
  { 0x4E00, 0x9FFF, 1925 },
  { 0xA000, 0xA48F, 1948 },
  { 0xA490, 0xA4CF, 1961 },
  { 0xA4D0, 0xA4FF, 1973 },
  { 0xA500, 0xA63F, 1978 },
  { 0xA640, 0xA69F, 1982 },
  { 0xA6A0, 0xA6FF, 2002 },
  { 0xA700, 0xA71F, 2008 },
  { 0xA720, 0xA7FF, 2030 },
  { 0xA800, 0xA82F, 2047 },
  { 0xA830, 0xA83F, 2060 },
  { 0xA840, 0xA87F, 2086 },
  { 0xA880, 0xA8DF, 2095 },
  { 0xA8E0, 0xA8FF, 2106 },
  { 0xA900, 0xA92F, 2126 },
  { 0xA930, 0xA95F, 2135 },
  { 0xA960, 0xA97F, 2142 },
  { 0xA980, 0xA9DF, 2165 },
  { 0xA9E0, 0xA9FF, 2174 },
  { 0xAA00, 0xAA5F, 2193 },
  { 0xAA60, 0xAA7F, 2198 },
  { 0xAA80, 0xAADF, 2217 },
  { 0xAAE0, 0xAAFF, 2226 },
  { 0xAB00, 0xAB2F, 2250 },
  { 0xAB30, 0xAB6F, 2270 },
  { 0xAB70, 0xABBF, 2287 },
  { 0xABC0, 0xABFF, 2307 },
  { 0xAC00, 0xD7AF, 2320 },
  { 0xD7B0, 0xD7FF, 2337 },
  { 0xD800, 0xDB7F, 2360 },
  { 0xDB80, 0xDBFF, 2376 },
  { 0xDC00, 0xDFFF, 2404 },
  { 0xE000, 0xF8FF, 2419 },
  { 0xF900, 0xFAFF, 2436 },
  { 0xFB00, 0xFB4F, 2465 },
  { 0xFB50, 0xFDFF, 2495 },
  { 0xFE00, 0xFE0F, 2523 },
  { 0xFE10, 0xFE1F, 2543 },
  { 0xFE20, 0xFE2F, 2558 },
  { 0xFE30, 0xFE4F, 2579 },
  { 0xFE50, 0xFE6F, 2603 },
  { 0xFE70, 0xFEFF, 2623 },
  { 0xFF00, 0xFFEF, 2651 },
  { 0xFFF0, 0xFFFF, 2681 },
  { 0x10000, 0x1007F, 2690 },
  { 0x10080, 0x100FF, 2709 },
  { 0x10100, 0x1013F, 2728 },
  { 0x10140, 0x1018F, 2743 },
  { 0x10190, 0x101CF, 2765 },
  { 0x101D0, 0x101FF, 2781 },
  { 0x10280, 0x1029F, 2795 },
  { 0x102A0, 0x102DF, 2802 },
  { 0x102E0, 0x102FF, 2809 },
  { 0x10300, 0x1032F, 2830 },
  { 0x10330, 0x1034F, 2841 },
  { 0x10350, 0x1037F, 2848 },
  { 0x10380, 0x1039F, 2859 },
  { 0x103A0, 0x103DF, 2868 },
  { 0x10400, 0x1044F, 2880 },
  { 0x10450, 0x1047F, 2888 },
  { 0x10480, 0x104AF, 2896 },
  { 0x104B0, 0x104FF, 2904 },
  { 0x10500, 0x1052F, 2910 },
  { 0x10530, 0x1056F, 2918 },
  { 0x10600, 0x1077F, 2937 },
  { 0x10800, 0x1083F, 2946 },
  { 0x10840, 0x1085F, 2964 },
  { 0x10860, 0x1087F, 2981 },
  { 0x10880, 0x108AF, 2991 },
  { 0x108E0, 0x108FF, 3001 },
  { 0x10900, 0x1091F, 3008 },
  { 0x10920, 0x1093F, 3019 },
  { 0x10980, 0x1099F, 3026 },
  { 0x109A0, 0x109FF, 3047 },
  { 0x10A00, 0x10A5F, 3064 },
  { 0x10A60, 0x10A7F, 3075 },
  { 0x10A80, 0x10A9F, 3093 },
  { 0x10AC0, 0x10AFF, 3111 },
  { 0x10B00, 0x10B3F, 3122 },
  { 0x10B40, 0x10B5F, 3130 },
  { 0x10B60, 0x10B7F, 3153 },
  { 0x10B80, 0x10BAF, 3175 },
  { 0x10C00, 0x10C4F, 3191 },
  { 0x10C80, 0x10CFF, 3202 },
  { 0x10E60, 0x10E7F, 3216 },
  { 0x11000, 0x1107F, 3237 },
  { 0x11080, 0x110CF, 3244 },
  { 0x110D0, 0x110FF, 3251 },
  { 0x11100, 0x1114F, 3264 },
  { 0x11150, 0x1117F, 3271 },
  { 0x11180, 0x111DF, 3280 },
  { 0x111E0, 0x111FF, 3288 },
  { 0x11200, 0x1124F, 3312 },
  { 0x11280, 0x112AF, 3319 },
  { 0x112B0, 0x112FF, 3327 },
  { 0x11300, 0x1137F, 3337 },
  { 0x11400, 0x1147F, 3345 },
  { 0x11480, 0x114DF, 3350 },
  { 0x11580, 0x115FF, 3358 },
  { 0x11600, 0x1165F, 3366 },
  { 0x11660, 0x1167F, 3371 },
  { 0x11680, 0x116CF, 3392 },
  { 0x11700, 0x1173F, 3398 },
  { 0x118A0, 0x118FF, 3403 },
  { 0x11A00, 0x11A4F, 3415 },
  { 0x11A50, 0x11AAF, 3432 },
  { 0x11AC0, 0x11AFF, 3440 },
  { 0x11C00, 0x11C6F, 3452 },
  { 0x11C70, 0x11CBF, 3462 },
  { 0x11D00, 0x11D5F, 3470 },
  { 0x12000, 0x123FF, 3484 },
  { 0x12400, 0x1247F, 3494 },
  { 0x12480, 0x1254F, 3528 },
  { 0x13000, 0x1342F, 3553 },
  { 0x14400, 0x1467F, 3574 },
  { 0x16800, 0x16A3F, 3596 },
  { 0x16A40, 0x16A6F, 3613 },
  { 0x16AD0, 0x16AFF, 3617 },
  { 0x16B00, 0x16B8F, 3627 },
  { 0x16F00, 0x16F9F, 3640 },
  { 0x16FE0, 0x16FFF, 3645 },
  { 0x17000, 0x187FF, 3681 },
  { 0x18800, 0x18AFF, 3688 },
  { 0x1B000, 0x1B0FF, 3706 },
  { 0x1B100, 0x1B12F, 3722 },
  { 0x1B170, 0x1B2FF, 3738 },
  { 0x1BC00, 0x1BC9F, 3744 },
  { 0x1BCA0, 0x1BCAF, 3753 },
  { 0x1D000, 0x1D0FF, 3779 },
  { 0x1D100, 0x1D1FF, 3805 },
  { 0x1D200, 0x1D24F, 3821 },
  { 0x1D300, 0x1D35F, 3852 },
  { 0x1D360, 0x1D37F, 3874 },
  { 0x1D400, 0x1D7FF, 3896 },
  { 0x1D800, 0x1DAAF, 3930 },
  { 0x1E000, 0x1E02F, 3949 },
  { 0x1E800, 0x1E8DF, 3971 },
  { 0x1E900, 0x1E95F, 3985 },
  { 0x1EE00, 0x1EEFF, 3991 },
  { 0x1F000, 0x1F02F, 4030 },
  { 0x1F030, 0x1F09F, 4044 },
  { 0x1F0A0, 0x1F0FF, 4057 },
  { 0x1F100, 0x1F1FF, 4071 },
  { 0x1F200, 0x1F2FF, 4104 },
  { 0x1F300, 0x1F5FF, 4136 },
  { 0x1F600, 0x1F64F, 4174 },
  { 0x1F650, 0x1F67F, 4184 },
  { 0x1F680, 0x1F6FF, 4204 },
  { 0x1F700, 0x1F77F, 4230 },
  { 0x1F780, 0x1F7FF, 4249 },
  { 0x1F800, 0x1F8FF, 4275 },
  { 0x1F900, 0x1F9FF, 4297 },
  { 0x20000, 0x2A6DF, 4334 },
  { 0x2A700, 0x2B73F, 4369 },
  { 0x2B740, 0x2B81F, 4404 },
  { 0x2B820, 0x2CEAF, 4439 },
  { 0x2CEB0, 0x2EBEF, 4474 },
  { 0x2F800, 0x2FA1F, 4509 },
  { 0xE0000, 0xE007F, 4549 },
  { 0xE0100, 0xE01EF, 4554 },
  { 0xF0000, 0xFFFFF, 4585 },
  { 0x100000, 0x10FFFF, 4618 },
};

#endif  /* #ifndef UNICODE_BLOCKS_H */
