font_manager_VALASOURCES = \
./Application.vala \
./Common/About.vala \
./Common/ArchiveManager.vala \
./Common/Collections.vala \
./Common/Constants.vala \
./Common/Database.vala \
./Common/FontInfo.vala \
./Common/Library.vala \
./Common/Logger.vala \
./Common/Main.vala \
./Common/Utils.vala \
./Filters/Category.vala \
./Filters/Collection.vala \
./Filters/Disabled.vala \
./Filters/Filter.vala \
./Filters/SearchResult.vala \
./Filters/Unsorted.vala \
./FontConfig/Accept.vala \
./FontConfig/DefaultProperties.vala \
./FontConfig/Directories.vala \
./FontConfig/DisplayProperties.vala \
./FontConfig/Enums.vala \
./FontConfig/Families.vala \
./FontConfig/Family.vala \
./FontConfig/FontConfig.vala \
./FontConfig/FontProperties.vala \
./FontConfig/FontSource.vala \
./FontConfig/Font.vala \
./FontConfig/Properties.vala \
./FontConfig/Reject.vala \
./FontConfig/Selections.vala \
./FontConfig/Sources.vala \
./FontConfig/XmlWriter.vala \
./Glue/Glue.vala \
./Json/Cacheable.vala \
./Json/JsonWriter.vala \
./Models/CategoryModel.vala \
./Models/CollectionModel.vala \
./Models/FontModel.vala \
./Models/UserFontModel.vala \
./UX/CharacterMap/CharacterDetails.vala \
./UX/CharacterMap/CharacterMapPane.vala \
./UX/CharacterMap/CharacterMapSideBar.vala \
./UX/CharacterMap/CharacterMap.vala \
./UX/CharacterMap/CharacterTable.vala \
./UX/Controls/BaseControls.vala \
./UX/Controls/CollectionControls.vala \
./UX/Controls/CompareControls.vala \
./UX/Controls/FontListControls.vala \
./UX/Controls/PreviewControls.vala \
./UX/Controls/TitleBar.vala \
./UX/Dialogs/FileSelector.vala \
./UX/Dialogs/Migration.vala \
./UX/Dialogs/NotImplemented.vala \
./UX/FontConfig/DisplayPropertiesPane.vala \
./UX/FontConfig/FontPropertiesPane.vala \
./UX/FontConfig/PropertiesEditor.vala \
./UX/FontConfig/SubpixelGeometry.vala \
./UX/MainWindow.vala \
./UX/Sidebar/MainSideBar.vala \
./UX/Sidebar/SideBar.vala \
./UX/State.vala \
./UX/Trees/CategoryTree.vala \
./UX/Trees/CollectionTree.vala \
./UX/Trees/FontListTree.vala \
./UX/Trees/UserFontTree.vala \
./UX/Trees/UserSourceList.vala \
./UX/Utils/Color.vala \
./UX/Utils/Utils.vala \
./UX/Viewer.vala \
./UX/Views/Browse.vala \
./UX/Views/Compare.vala \
./UX/Views/FontPreview.vala \
./UX/Views/Metadata.vala \
./UX/Widgets/ActivePreview.vala \
./UX/Widgets/AdjustablePreview.vala \
./UX/Widgets/CellRendererPill.vala \
./UX/Widgets/FontScale.vala \
./UX/Widgets/LabeledSpinButton.vala \
./UX/Widgets/LabeledSwitch.vala \
./UX/Widgets/OptionScale.vala \
./UX/Widgets/ReactiveLabel.vala \
./UX/Widgets/TextPreview.vala \
./UX/Widgets/TextViews.vala \
./UX/Widgets/ThinPaned.vala \
./UX/Widgets/TreeViews.vala \
./UX/Widgets/WaterfallPreview.vala 
