# Do not edit directly. See build-aux directory

libfontmanager_la_VALASOURCES = \
	Common/About.vala \
	Common/ArchiveManager.vala \
	Common/Cacheable.vala \
	Common/Collections.vala \
	Common/Constants.vala \
	Common/Database.vala \
	Common/FontData.vala \
	Common/FontInfo.vala \
	Common/JsonWriter.vala \
	Common/Logger.vala \
	Common/Settings.vala \
	Common/Utils.vala \
	Filters/Category.vala \
	Filters/Collection.vala \
	Filters/Disabled.vala \
	Filters/Filter.vala \
	Filters/SearchResult.vala \
	Filters/Unsorted.vala \
	FontConfig/Alias.vala \
	FontConfig/Common.vala \
	FontConfig/Directories.vala \
	FontConfig/Enums.vala \
	FontConfig/Families.vala \
	FontConfig/Family.vala \
	FontConfig/Font.vala \
	FontConfig/MonitoredFiles.vala \
	FontConfig/Properties.vala \
	FontConfig/Selections.vala \
	FontConfig/Sources.vala \
	FontConfig/XmlWriter.vala \
	Glue/Glue.vala \
	Library/Install.vala \
	Library/Library.vala \
	Library/Query.vala \
	Library/Remove.vala \
	Library/Sorter.vala \
	UX/CharacterMap/CharacterDetails.vala \
	UX/CharacterMap/CharacterMapSideBar.vala \
	UX/CharacterMap/CharacterTable.vala \
	UX/Controls/BaseControls.vala \
	UX/Controls/CollectionControls.vala \
	UX/Controls/FontListControls.vala \
	UX/Controls/PreviewControls.vala \
	UX/FontConfig/Controls.vala \
	UX/FontConfig/DisplayPropertiesPane.vala \
	UX/FontConfig/FontPropertiesPane.vala \
	UX/FontConfig/FontSourceList.vala \
	UX/FontConfig/PreferencePane.vala \
	UX/FontConfig/SubpixelGeometry.vala \
	UX/FontConfig/Substitute.vala \
	UX/Metadata/Description.vala \
	UX/Metadata/License.vala \
	UX/Metadata/Properties.vala \
	UX/Models/CategoryModel.vala \
	UX/Models/CollectionModel.vala \
	UX/Models/FontModel.vala \
	UX/Models/UserFontModel.vala \
	UX/Trees/CategoryTree.vala \
	UX/Trees/CollectionTree.vala \
	UX/Trees/FontListTree.vala \
	UX/Trees/UserFontTree.vala \
	UX/Utils/Color.vala \
	UX/Utils/FileSelector.vala \
	UX/Utils/Utils.vala \
	UX/Views/FontPreviewPane.vala \
	UX/Widgets/CellRendererPill.vala \
	UX/Widgets/Controls.vala \
	UX/Widgets/Labels.vala \
	UX/Widgets/TextViews.vala \
	UX/Widgets/TreeViews.vala 
