.TH FONT-MANAGER 1 "June 21, 2014"
.SH NAME
font-manager \- A simple font management application for Gtk+ Desktop Environments
.SH SYNOPSIS
.B font-manager
.SH DESCRIPTION
This manual page documents briefly the
.B font-manager command.
.PP
\fBFont Manager\fP is intended to provide a way for average users to easily manage desktop fonts, without having to resort to command line tools or editing configuration files by hand. While designed primarily with the Gnome Desktop Environment in mind, it should work well with other Gtk+ desktop environments.

Font Manager is NOT intended to be a professional-grade font management solution.
.PP
.B font-manager
has been written in Vala using Gtk+ 3, after installing the application
you can run it from the
.B Applications
menu.
.SH AUTHOR
font-manager was written by Jerry Casiano <jerrycasiano@gmail.com>.
.PP
This manual page was written by Alessio Treglia <alessio@debian.org>,
for the Debian project (and may be used by others).
