usr/bin/font-manager
usr/share/metainfo/com.github.FontManager.FontManager.appdata.xml
usr/share/applications/com.github.FontManager.FontManager.desktop
usr/share/dbus-1/services/com.github.FontManager.FontManager.service
usr/share/gnome-shell/search-providers/com.github.FontManager.FontManager.SearchProvider.ini
usr/share/icons/hicolor/scalable/apps/com.github.FontManager.FontManager.svg
usr/share/icons/hicolor/symbolic/apps/com.github.FontManager.FontManager.svg
